name: Build and Test

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release, Debug]
        platform: [x64, Win32]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build Libraries
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.platform}} ${{env.SOLUTION_FILE_PATH}}

    - name: Core Tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ${{matrix.platform}}/${{matrix.configuration}}/core_tests.exe

    - name: Dll Tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ${{matrix.platform}}/${{matrix.configuration}}/dll_tests.exe

    - name: Build Example sender
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.platform}} ./examples/sender/sender.sln

    - name: Build Example softcam_installer
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.platform}} ./examples/softcam_installer/softcam_installer.sln

    - name: Build Example python_binding
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: |
        cd examples/python_binding
        echo yes | call DownloadPybind11.bat
        python -c "import sys;print(sys.prefix)" > _python_dir.txt
        set /p PYTHON_DIR=<_python_dir.txt
        del _python_dir.txt
        set PYTHON_INCLUDE_DIR=%PYTHON_DIR%\include
        set PYTHON_LIBS_DIR=%PYTHON_DIR%\libs
        msbuild /m /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.platform}} ./python_binding.sln
